### ISSUE TITLE
Add figure alt text as caption

### ISSUE THREAD

**Issue by dhersz** [nanxstats/hugo-nanx2020#1]
Hello, and sorry for bugging you again.

I'm playing with the website style a bit (and, really, I try to mimick a lot of what you've done in your personal website because I really like how it's styled) and realized I can't get to center the images and place the alt text as their caption, as you do in your website.

I tried to understand what is going on and realized that my `.html` files and your `.html` files are not being generated the same way from the `.Rmd` files. Since the `.css` files are styling some classes that don't show up in my `.html` the figures and captions are not being properly styled.

An example. In your last post, you had an image in the `.Rmd` like so:
```rmd
![A screenshot of the updated Hugo Tanka theme.](/image/hugo-tanka-theme-bootstrap.png)
```

And the `html` generated from it:
````html
<div class="figure">
<img src="https://nanx.me/image/hugo-tanka-theme-bootstrap.png" alt="" />
<p class="caption">A screenshot of the updated Hugo Tanka theme.</p>
</div>
````

So I tried to do a similar thing (ignore the random alt text lol):
```rmd
![hello my friends](/publication/anpet-2020.pt_files/34-anpet.png){width=200px}
```

Which results in:
```html
<img src="/publication/anpet-2020.pt_files/34-anpet.png" width="200" alt="hello my friends" />
```

Are you using a custom Rmarkdown renderer, or something like it? I tried searching for answers in the internet, but couldn't find anything useful, so I figured out maybe I should just ask you.

Again, thank you very much for the theme and congrats for the beautiful website. Cheers

**Comment by nanxstats** [comment]
@dhersz Yes, the differences are probably from the Markdown toolchain.

Since I use [blogdown](https://bookdown.org/yihui/blogdown/) to generate my website, the toolchain looks like this:

R Markdown -> Markdown -> pandoc -> html in `content/` -> Hugo (Goldmark) -> html in `public/`

While if you use plain Markdown in blogdown or Hugo the toolchain would likely be much simpler:

Markdown -> Hugo (Goldmark) -> html in `public/`

I'm not sure if there is a good solution for the images caption if one uses Markdown from the theme side (maybe there is). Although not very elegant, you can always write the raw HTML there as an ad-hoc solution:

```html
<div class="figure">
<img src="https://example.com/example.png" alt="">
<p class="caption">Caption text.</p>
</div>
```

**Comment by dhersz** [comment]
@nanxstats Thank you for the response! 

What is weird is that I'm also using blogdown and writing my posts and page in R Markdown. But after testing once again to make sure I wasn't doing anything wrong it worked as expected, so I guess I was in fact doing something wrong which I have no ideia what it was lol

I apologize for the inconvenience, and thank you again :)
